"""Implementation of the ``init-run`` subcommand.

Starting a Run means: generate a unique run id, resolve the directory this
run's on-disk state lives in, create that run's audit log file inside it,
and write the run-start entry (Req 9.1).

The state directory is resolved entirely through :mod:`pathlib`, never a
hardcoded POSIX (``/tmp/...``) or Windows (``C:\\...``) literal, per the
Cross-Platform Considerations in design.md. Production default: a
subdirectory of :func:`tempfile.gettempdir`, which resolves to an
OS-appropriate temp location on Windows, Linux, and macOS alike. That
default can be overridden - purely for test isolation - either by passing
``state_dir`` explicitly or by setting the ``AZQT_STATE_DIR`` environment
variable; neither mechanism changes the production default behavior when
left unset.
"""

from __future__ import annotations

import os
import tempfile
import uuid
from pathlib import Path
from typing import Any

from azqt.audit.logger import AuditLogger

#: Name of the subdirectory (under the resolved state base) that holds every
#: run's audit log file.
_RUNS_SUBDIR = "azqt-runs"


def generate_run_id() -> str:
    """Return a run id unique across invocations.

    A UUID4 hex string is used: it requires no extra dependency, carries
    effectively no collision risk across the lifetime of any real Run, and
    is safe to use verbatim as a filename component on every OS this tool
    targets (Windows, Linux, macOS all forbid nothing in a plain hex
    string).
    """

    return uuid.uuid4().hex


def default_state_dir() -> Path:
    """Resolve the base directory under which per-run state directories live.

    Reads the ``AZQT_STATE_DIR`` environment variable first, purely to let
    tests point this at ``tmp_path`` without needing to thread a parameter
    through every call site; when unset (the production case), it falls
    back to a fixed subdirectory of :func:`tempfile.gettempdir`, which is
    itself always resolved via :class:`pathlib.Path` rather than any
    hardcoded platform-specific literal.
    """

    override = os.environ.get("AZQT_STATE_DIR")
    if override:
        return Path(override)
    return Path(tempfile.gettempdir()) / _RUNS_SUBDIR


def log_path_for_run(run_id: str, *, state_dir: Path | None = None) -> Path:
    """Return the audit log path created for ``run_id`` by :func:`init_run`.

    Every CLI subcommand receives only a run id, so this small shared lookup
    keeps the persistent audit path derivation consistent with ``init-run``.
    The run id is deliberately constrained to the UUID4 hexadecimal format
    generated by :func:`generate_run_id`, preventing a CLI argument from
    escaping the configured state directory.
    """

    if not run_id or any(char not in "0123456789abcdef" for char in run_id) or len(run_id) != 32:
        raise ValueError("Invalid run id.")
    base_dir = Path(state_dir) if state_dir is not None else default_state_dir()
    log_path = base_dir / f"{run_id}.jsonl"
    if not log_path.is_file():
        raise ValueError(f"No audit log exists for run {run_id}.")
    return log_path


def init_run(document: str | Path, *, state_dir: Path | None = None) -> dict[str, Any]:
    """Start a Run for the given Quota_Request_Document.

    Generates a run id, ensures the per-run state directory exists, creates
    that run's audit log file, and appends the run-start entry containing
    the document path (the entry's own timestamp field, populated by
    :class:`~azqt.audit.logger.AuditEvent`, satisfies the start-timestamp
    part of Req 9.1).

    Returns a dict with ``run_id`` (str), ``log_path`` (:class:`pathlib.Path`),
    and ``write_failed`` (bool, mirroring the Audit_Logger's best-effort
    write outcome for the run-start entry).
    """

    run_id = generate_run_id()
    base_dir = Path(state_dir) if state_dir is not None else default_state_dir()
    base_dir.mkdir(parents=True, exist_ok=True)

    log_path = base_dir / f"{run_id}.jsonl"
    logger = AuditLogger(log_path)

    document_path = str(Path(document))
    ok = logger.log("run-start", {"run_id": run_id, "document_path": document_path})

    return {"run_id": run_id, "log_path": log_path, "write_failed": not ok}
